twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      joystick:
        topic   : joy/cmd_vel
        timeout : 0.5
        priority: 100
      keyboard0:
        topic   : turtle1/cmd_vel
        timeout : 0.5
        priority: 100
      keyboard:
        topic   : key/cmd_vel
        timeout : 0.5
        priority: 100    